dist: xenial

language: php
php:
  - 8.1
  - 8.0
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
# - hhvm

before_script:
  - composer self-update
  - composer install --dev
  - composer require doctrine/dbal ^2.5

script:
  - ./vendor/bin/phpunit --verbose --colors=auto --coverage-text='php://stdout'

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
