dist: xenial

language: php
php:
  - 8.2
  - 8.1
  - 8.0
  - 7.4
  - 7.3
  - 7.2
# - hhvm

before_script:
  - composer self-update
  - composer install --dev
  - composer require doctrine/dbal ^2.5
  - echo -e "[xdebug]\nxdebug.mode = coverage" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug-cov.ini

script:
  - ./vendor/bin/phpunit --verbose --colors=auto --coverage-text='php://stdout'

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
